In [328]:
print("hello world")

hello world


In [329]:
import pandas as pd
import nltk
import re
import gensim
import numpy as np

In [330]:
messages = pd.read_csv(r"e:\NLP_practice\Data\spam.csv",   usecols=[0, 1],skiprows=1,  # Read only the first two columns
    names=["label", "message"],encoding="ISO-8859-1")
print(messages)

     label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham            Will �_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]


In [331]:

from nltk.stem import WordNetLemmatizer
WordNetLemmatize= WordNetLemmatizer()

In [332]:
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages["message"][i])
    review = review.lower()
    review = review.split()
    review = [WordNetLemmatize.lemmatize(word) for word in review ]
    review = ' '.join(review)
    corpus.append(review)

In [333]:
[[i,j,k] for i,j,k in zip (list(map(len,corpus)),corpus,messages['message']) if i <1]

[[0, '', '645'], [0, '', ':) '], [0, '', ':-) :-)']]

In [334]:
corpus

['go until jurong point crazy available only in bugis n great world la e buffet cine there got amore wat',
 'ok lar joking wif u oni',
 'free entry in a wkly comp to win fa cup final tkts st may text fa to to receive entry question std txt rate t c s apply over s',
 'u dun say so early hor u c already then say',
 'nah i don t think he go to usf he life around here though',
 'freemsg hey there darling it s been week s now and no word back i d like some fun you up for it still tb ok xxx std chgs to send to rcv',
 'even my brother is not like to speak with me they treat me like aid patent',
 'a per your request melle melle oru minnaminunginte nurungu vettam ha been set a your callertune for all caller press to copy your friend callertune',
 'winner a a valued network customer you have been selected to receivea prize reward to claim call claim code kl valid hour only',
 'had your mobile month or more u r entitled to update to the latest colour mobile with camera for free call the mobile up

In [335]:
from nltk import sent_tokenize
from gensim.utils  import simple_preprocess


In [336]:
words=[]
for sent in corpus:
    sent_token= sent_tokenize(sent)
    for word in sent_token:
        words.append(simple_preprocess(word))


In [337]:
words[1]

['ok', 'lar', 'joking', 'wif', 'oni']

In [338]:
##let train word2vec from scratch
model=gensim.models.Word2Vec(words)

In [339]:
#to get all vocabulary
model.wv.index_to_key



['you',
 'to',
 'the',
 'and',
 'it',
 'in',
 'is',
 'me',
 'my',
 'for',
 'your',
 'call',
 'of',
 'that',
 'have',
 'on',
 'now',
 'are',
 'can',
 'so',
 'but',
 'not',
 'or',
 'we',
 'do',
 'get',
 'at',
 'be',
 'if',
 'will',
 'ur',
 'with',
 'no',
 'just',
 'this',
 'gt',
 'lt',
 'how',
 'go',
 'up',
 'when',
 'ok',
 'day',
 'what',
 'free',
 'from',
 'out',
 'all',
 'know',
 'll',
 'come',
 'like',
 'time',
 'good',
 'then',
 'am',
 'got',
 'wa',
 'there',
 'he',
 'text',
 'only',
 'love',
 'want',
 'send',
 'txt',
 'need',
 'one',
 'today',
 'by',
 'going',
 'don',
 'home',
 'stop',
 'about',
 'she',
 'lor',
 'sorry',
 'see',
 'still',
 'mobile',
 'take',
 'back',
 'da',
 'reply',
 'our',
 'think',
 'dont',
 'tell',
 'week',
 'phone',
 'hi',
 'new',
 'later',
 'they',
 'her',
 'any',
 'pls',
 'ha',
 'please',
 'co',
 'did',
 'msg',
 'been',
 'min',
 'some',
 'an',
 'make',
 'dear',
 'here',
 'night',
 'who',
 'message',
 'say',
 'well',
 're',
 'where',
 'thing',
 'much',
 'clai

In [340]:
model.corpus_count

5569

In [341]:
model.epochs

5

In [342]:
model.wv.similar_by_word('good')

[('day', 0.9990065693855286),
 ('wa', 0.9988637566566467),
 ('morning', 0.9988102912902832),
 ('where', 0.998778760433197),
 ('about', 0.9987170696258545),
 ('amp', 0.998601496219635),
 ('should', 0.998590350151062),
 ('happy', 0.9985828399658203),
 ('all', 0.9985764026641846),
 ('night', 0.9985552430152893)]

In [343]:
model.wv['good'].shape

(100,)

In [344]:
words[8]

['winner',
 'valued',
 'network',
 'customer',
 'you',
 'have',
 'been',
 'selected',
 'to',
 'receivea',
 'prize',
 'reward',
 'to',
 'claim',
 'call',
 'claim',
 'code',
 'kl',
 'valid',
 'hour',
 'only']

In [345]:
model.wv['go']

array([-0.3367306 ,  0.29676557,  0.29088587,  0.22330834,  0.17946394,
       -0.7318847 ,  0.2414202 ,  0.843711  , -0.3228777 , -0.27698815,
       -0.32162657, -0.6876291 , -0.12419428,  0.20009606,  0.19951802,
       -0.3248117 ,  0.08834962, -0.52894676, -0.005405  , -0.78442127,
        0.2712155 ,  0.2822952 ,  0.24635844, -0.22351865, -0.00150526,
        0.10943113, -0.3353473 , -0.37830344, -0.39095262,  0.02414072,
        0.4070314 ,  0.04823976,  0.19239789, -0.25297704, -0.17025878,
        0.55203766,  0.04750759, -0.34986326, -0.06301853, -0.8028999 ,
        0.15119681, -0.26585257, -0.31577587,  0.04918677,  0.29037592,
       -0.16272695, -0.19683881, -0.11146721,  0.17025083,  0.28554294,
        0.20542982, -0.28244248, -0.12242781,  0.04735848, -0.19573951,
        0.19866191,  0.2181726 ,  0.19292912, -0.57029986,  0.2763498 ,
       -0.01377532, -0.0300937 ,  0.1419112 , -0.1255664 , -0.5532207 ,
        0.3364871 ,  0.15782401,  0.28193533, -0.5182983 ,  0.52

In [346]:
def avg_word2vec(doc):
    return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key],axis=0)
  

In [347]:
import tqdm

In [348]:
from tqdm import tqdm

In [349]:
#apply for the entire sentences
X=[]
for i in tqdm(range(len(words))):
  
    X.append(avg_word2vec(words[i]))

  5%|▌         | 306/5569 [00:00<00:01, 2788.68it/s]e:\NLP_practice\venv\Lib\site-packages\numpy\core\fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
e:\NLP_practice\venv\Lib\site-packages\numpy\core\_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
100%|██████████| 5569/5569 [00:01<00:00, 4765.30it/s]


In [350]:
X[2].shape

(100,)

In [351]:
len(X)

5569

In [352]:
X[2].shape

(100,)

In [353]:
X[0].reshape(1,-1).shape

(1, 100)

In [354]:
X_new = np.array(X, dtype=object)


In [355]:
messages.shape

(5572, 2)

In [356]:
X_new[0].reshape(1,-1).shape

(1, 100)

In [357]:
X_new

array([array([-0.20417689,  0.2066011 ,  0.19675131,  0.15627605,  0.09756858,
              -0.48093364,  0.17551075,  0.554577  , -0.22136892, -0.17172565,
              -0.20831244, -0.4423996 , -0.08167198,  0.11916885,  0.14223385,
              -0.19693509,  0.04175172, -0.33985087, -0.00280374, -0.50122595,
               0.1662633 ,  0.18550219,  0.16057827, -0.1613478 , -0.00609674,
               0.07984311, -0.21889013, -0.2349184 , -0.27550447, -0.00317647,
               0.25394502,  0.02986761,  0.13730687, -0.18227743, -0.11183315,
               0.36008683,  0.0514776 , -0.24277548, -0.07987407, -0.51535046,
               0.06881722, -0.17098556, -0.21056484,  0.03670995,  0.203907  ,
              -0.12694287, -0.12388174, -0.06699385,  0.11003233,  0.19103183,
               0.13680868, -0.18271375, -0.11187363,  0.02003378, -0.11896483,
               0.1167125 ,  0.14829989,  0.13221447, -0.3613402 ,  0.15054253,
              -0.03375172, -0.01558349,  0.09134783,

In [358]:
##dependet feature
##output features
y= messages[list(map(lambda x: len(x)>0,corpus))]
y = pd.get_dummies(y['label'])
y=y.iloc[:,0].values

In [302]:
y

array([ True,  True, False, ...,  True,  True,  True])

In [363]:
y

array([ True,  True, False, ...,  True,  True,  True])

In [376]:
y=y.astype(int)

In [377]:
df_list = [pd.DataFrame(X_new[i].reshape(1, -1)) for i in range(len(X_new))]
df = pd.concat(df_list, ignore_index=True)


C:\Users\Suraj Kumar\AppData\Local\Temp\ipykernel_14528\1842544085.py:2: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(df_list, ignore_index=True)


In [378]:
df.shape

(5569, 100)

In [379]:
df['output']=y

In [380]:
df.dropna(axis=0,inplace=True)

In [381]:
X=df

In [382]:
X.isnull().sum()

0         0
1         0
2         0
3         0
4         0
         ..
96        0
97        0
98        0
99        0
output    0
Length: 101, dtype: int64

In [383]:
y.shape

(5557,)

In [384]:
y=df['output']

In [385]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X,y,test_size=0.20)

In [386]:
y_train

1157    1.0
2423    1.0
5151    1.0
508     1.0
2875    1.0
       ... 
5504    1.0
2707    1.0
3432    1.0
2369    1.0
2899    0.0
Name: output, Length: 4445, dtype: float64

In [387]:
X_train

0         1         2         3         4         5         6  \
1157 -0.245822  0.242323  0.233338  0.177438  0.125016 -0.570165  0.204171   
2423 -0.267496  0.267389  0.257440  0.185001  0.130070 -0.613049  0.247030   
5151 -0.102048  0.376579  0.227388  0.248898 -0.118741 -0.528817  0.475330   
508  -0.286920  0.286304  0.265251  0.170133  0.172813 -0.676291  0.247327   
2875 -0.253734  0.244067  0.247419  0.194233  0.123830 -0.589634  0.204925   
...        ...       ...       ...       ...       ...       ...       ...   
5504 -0.254075  0.241420  0.242606  0.176782  0.136884 -0.597938  0.207050   
2707 -0.055322  0.054445  0.047601  0.038964  0.032276 -0.121233  0.046644   
3432 -0.229709  0.217775  0.229827  0.175143  0.125861 -0.551553  0.178544   
2369 -0.221045  0.221121  0.211649  0.149944  0.110742 -0.519995  0.204712   
2899 -0.260723  0.240365  0.268266  0.242460  0.122832 -0.611952  0.184362   

             7         8         9  ...        91        92        93  \
1157  0.661183 -0.263689 -0.213727  ...  0.244778 -0.008982  0.132820   
2423  0.716312 -0.278923 -0.236530  ...  0.268967 -0.007858  0.149837   
5151  0.679733 -0.289925 -0.210479  ...  0.476963  0.115637  0.183232   
508   0.788107 -0.316670 -0.264041  ...  0.297318 -0.015456  0.161727   
2875  0.678682 -0.275948 -0.211873  ...  0.252691 -0.014080  0.133099   
...        ...       ...       ...  ...       ...       ...       ...   
5504  0.688034 -0.272647 -0.229383  ...  0.239872 -0.013609  0.138782   
2707  0.128818 -0.042338 -0.040332  ...  0.045351 -0.006470  0.018555   
3432  0.621932 -0.247524 -0.206237  ...  0.223667 -0.022090  0.123670   
2369  0.604350 -0.238446 -0.194639  ...  0.224930 -0.008425  0.123507   
2899  0.689499 -0.296760 -0.187470  ...  0.262265 -0.015716  0.134241   

            94        95        96        97        98        99  output  
1157  0.509616  0.280791  0.175349 -0.199190  0.023022 -0.100026     1.0  
2423  0.561801  0.308571  0.199724 -0.220861  0.042205 -0.114451     1.0  
5151  0.608491  0.361226  0.406988  0.168392 -0.078074 -0.226534     1.0  
508   0.634071  0.350405  0.198852 -0.257116  0.049535 -0.109176     1.0  
2875  0.520268  0.284599  0.173091 -0.198590  0.021110 -0.098139     1.0  
...        ...       ...       ...       ...       ...       ...     ...  
5504  0.531051  0.295486  0.169512 -0.224283  0.014534 -0.082878     1.0  
2707  0.102763  0.048278  0.031281 -0.034711  0.001963 -0.021371     1.0  
3432  0.472563  0.276506  0.139641 -0.204869  0.024952 -0.086124     1.0  
2369  0.476132  0.260626  0.170018 -0.183339  0.027183 -0.094703     1.0  
2899  0.516459  0.299846  0.167297 -0.180164  0.002530 -0.098725     0.0  

[4445 rows x 101 columns]

In [391]:
X_train.columns = X_train.columns.astype(str)
X_test.columns = X_test.columns.astype(str)  # If applicable


In [392]:
from sklearn.ensemble import RandomForestClassifier
classifier= RandomForestClassifier()


In [393]:
classifier.fit(X_train,y_train)

RandomForestClassifier()

In [394]:
y_pred= classifier.predict(X_test)

In [396]:
from sklearn.metrics import accuracy_score, classification_report

In [397]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       1.00      0.97      0.99       149
         1.0       1.00      1.00      1.00       963

    accuracy                           1.00      1112
   macro avg       1.00      0.99      0.99      1112
weighted avg       1.00      1.00      1.00      1112

